/**
 * Static fixture data for the seed generator: name pools, the per-weekend team
 * template and candidate life-situation profiles.
 */
import type { CHARole, Rollo } from '@/lib/weekend/types'

type Role = `${CHARole}`
type RolloName = `${Rollo}`

export const MALE_FIRST_NAMES = [
  'James',
  'John',
  'Robert',
  'Michael',
  'William',
  'David',
  'Richard',
  'Joseph',
  'Thomas',
  'Charles',
  'Daniel',
  'Matthew',
  'Anthony',
  'Mark',
  'Steven',
  'Paul',
  'Andrew',
  'Joshua',
  'Kenneth',
  'Kevin',
  'Brian',
  'George',
  'Timothy',
  'Ronald',
  'Jason',
  'Edward',
  'Jeffrey',
  'Ryan',
  'Jacob',
  'Gary',
  'Nicholas',
  'Eric',
  'Jonathan',
  'Stephen',
  'Larry',
  'Justin',
  'Scott',
  'Brandon',
  'Benjamin',
  'Samuel',
  'Gregory',
  'Alexander',
  'Patrick',
  'Frank',
  'Raymond',
  'Jack',
  'Dennis',
  'Jerry',
  'Tyler',
  'Aaron',
  'Jose',
  'Adam',
  'Nathan',
  'Henry',
  'Zachary',
  'Douglas',
  'Peter',
  'Kyle',
  'Noah',
  'Ethan',
  'Jeremy',
  'Walter',
  'Christian',
  'Keith',
  'Roger',
  'Terry',
  'Austin',
  'Sean',
  'Gerald',
  'Carl',
  'Harold',
  'Dylan',
  'Arthur',
  'Lawrence',
  'Jordan',
  'Jesse',
  'Bryan',
  'Billy',
  'Bruce',
  'Gabriel',
  'Joe',
  'Logan',
  'Alan',
  'Juan',
  'Albert',
  'Willie',
  'Elijah',
  'Wayne',
  'Randy',
  'Vincent',
  'Mason',
  'Roy',
  'Ralph',
  'Bobby',
  'Russell',
  'Bradley',
  'Philip',
  'Eugene',
  'Caleb',
  'Luke',
  'Isaac',
  'Micah',
  'Levi',
  'Silas',
] as const

export const FEMALE_FIRST_NAMES = [
  'Mary',
  'Patricia',
  'Jennifer',
  'Linda',
  'Elizabeth',
  'Barbara',
  'Susan',
  'Jessica',
  'Sarah',
  'Karen',
  'Lisa',
  'Nancy',
  'Betty',
  'Sandra',
  'Margaret',
  'Ashley',
  'Kimberly',
  'Emily',
  'Donna',
  'Michelle',
  'Carol',
  'Amanda',
  'Melissa',
  'Deborah',
  'Stephanie',
  'Dorothy',
  'Rebecca',
  'Sharon',
  'Laura',
  'Cynthia',
  'Amy',
  'Kathleen',
  'Angela',
  'Shirley',
  'Brenda',
  'Emma',
  'Anna',
  'Pamela',
  'Nicole',
  'Samantha',
  'Katherine',
  'Christine',
  'Helen',
  'Debra',
  'Rachel',
  'Carolyn',
  'Janet',
  'Maria',
  'Catherine',
  'Heather',
  'Diane',
  'Olivia',
  'Julie',
  'Joyce',
  'Victoria',
  'Ruth',
  'Virginia',
  'Lauren',
  'Kelly',
  'Christina',
  'Joan',
  'Evelyn',
  'Judith',
  'Andrea',
  'Hannah',
  'Megan',
  'Cheryl',
  'Jacqueline',
  'Martha',
  'Madison',
  'Teresa',
  'Gloria',
  'Sara',
  'Janice',
  'Ann',
  'Kathryn',
  'Abigail',
  'Sophia',
  'Frances',
  'Jean',
  'Alice',
  'Judy',
  'Isabella',
  'Julia',
  'Grace',
  'Amber',
  'Denise',
  'Danielle',
  'Marilyn',
  'Beverly',
  'Charlotte',
  'Natalie',
  'Theresa',
  'Diana',
  'Brittany',
  'Doris',
  'Kayla',
  'Alexis',
  'Lori',
  'Leah',
  'Naomi',
  'Lydia',
  'Esther',
  'Ruby',
] as const

export const LAST_NAMES = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Perez',
  'Thompson',
  'White',
  'Harris',
  'Sanchez',
  'Clark',
  'Ramirez',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
  'Flores',
  'Green',
  'Adams',
  'Nelson',
  'Baker',
  'Hall',
  'Rivera',
  'Campbell',
  'Mitchell',
  'Carter',
  'Roberts',
  'Gomez',
  'Phillips',
  'Evans',
  'Turner',
  'Diaz',
  'Parker',
  'Cruz',
  'Edwards',
  'Collins',
  'Reyes',
  'Stewart',
  'Morris',
  'Morales',
  'Murphy',
  'Cook',
  'Rogers',
  'Gutierrez',
  'Ortiz',
  'Morgan',
  'Cooper',
  'Peterson',
  'Bailey',
  'Reed',
  'Kelly',
  'Howard',
  'Ramos',
  'Kim',
  'Cox',
  'Ward',
  'Richardson',
  'Watson',
  'Brooks',
  'Chavez',
  'Wood',
  'James',
  'Bennett',
  'Gray',
  'Mendoza',
  'Ruiz',
  'Hughes',
  'Price',
  'Alvarez',
  'Castillo',
  'Sanders',
  'Patel',
  'Myers',
] as const

export const CHURCHES = [
  'First Baptist Church',
  'Grace Community Church',
  "St. Mary's Catholic Church",
  'Trinity Methodist Church',
  'Crossroads Bible Church',
  'Living Water Fellowship',
  'Hope Presbyterian Church',
  'Cornerstone Church',
  "St. Paul's Lutheran Church",
  'New Life Assembly',
] as const

export const CITIES = [
  { city: 'Abilene', zip: '79601' },
  { city: 'San Angelo', zip: '76901' },
  { city: 'Midland', zip: '79701' },
  { city: 'Odessa', zip: '79761' },
  { city: 'Lubbock', zip: '79401' },
  { city: 'Big Spring', zip: '79720' },
  { city: 'Sweetwater', zip: '79556' },
] as const

export const STREETS = [
  'Mesquite Dr',
  'Pecan St',
  'Ranch Rd',
  'Bluebonnet Ln',
  'Cedar Ridge Rd',
  'Prairie View Dr',
  'Caprock Ave',
  'Sagebrush Trl',
  'Windmill Way',
  'Canyon Creek Rd',
] as const

export const OTHER_COMMUNITIES = [
  'KAIROS',
  'TRES_DIAS',
  'WALK_TO_EMMAUS',
] as const

export const SHIRT_SIZES = ['S', 'M', 'L', 'XL', '2XL'] as const

export const MEETING_LOCATIONS = [
  'First Baptist Church',
  'Grace Fellowship Hall',
  'Community Chapel',
] as const

export const CAMP = 'Camp Tejas'

// -----------------------------------------------------------------------------
// Team template
// -----------------------------------------------------------------------------

/**
 * How demanding a slot is. Slots are filled in this order, each from the most
 * experienced people still available, so leaders have leadership history.
 */
export type SlotLevel = 'lead' | 'head' | 'rollista' | 'basic'

export type Slot = { role: Role; level: SlotLevel; rollo: RolloName | null }

const slot = (
  role: Role,
  level: SlotLevel,
  rollo: RolloName | null = null
): Slot => ({ role, level, rollo })

const repeat = (count: number, make: (i: number) => Slot): Slot[] =>
  Array.from({ length: count }, (_, i) => make(i))

const TABLE_LEADER_ROLLOS: RolloName[] = [
  'Ideals',
  'Church',
  'Piety',
  'Study',
  'Action',
  'Leaders',
  'Environments',
]

/**
 * Every position filled on a single (Men's or Women's) weekend, excluding the
 * spiritual directors, who are clergy serving both weekends of the group.
 */
export const WEEKEND_TEAM: Slot[] = [
  slot('Rector', 'lead', 'Fourth Day'),
  slot('Backup Rector', 'lead'),
  slot('Head', 'lead', 'Reunion Group'),
  slot('Assistant Head', 'lead', 'CCIA'),
  slot('Assistant Head', 'lead'),
  slot('Head Rollista', 'head', 'Holy Spirit'),
  ...repeat(7, (i) => slot('Table Leader', 'rollista', TABLE_LEADER_ROLLOS[i])),
  slot('Head Prayer', 'head'),
  ...repeat(2, () => slot('Prayer', 'basic')),
  slot('Head Chapel', 'head'),
  ...repeat(2, () => slot('Chapel', 'basic')),
  slot('Head Chapel Tech', 'head'),
  slot('Head Music', 'head'),
  ...repeat(3, () => slot('Music', 'basic')),
  slot('Head Tech', 'head'),
  ...repeat(2, () => slot('Tech', 'basic')),
  slot('Head Palanca', 'head'),
  ...repeat(2, () => slot('Palanca', 'basic')),
  slot('Head Table', 'head'),
  ...repeat(2, () => slot('Table', 'basic')),
  slot('Head Dorm', 'head'),
  ...repeat(2, () => slot('Dorm', 'basic')),
  slot('Head Dining', 'head'),
  ...repeat(4, () => slot('Dining', 'basic')),
  slot('Head Mobile', 'head'),
  ...repeat(2, () => slot('Mobile', 'basic')),
  slot('Escort', 'basic'),
  slot('Floater', 'basic'),
  slot('Roster', 'basic'),
  slot('Gopher', 'basic'),
  slot('Medic', 'basic'),
  slot('Storeroom', 'basic'),
  slot('Outside Prayer', 'basic'),
  slot('Smoker', 'basic'),
]

/** Clergy slots — the same people serve on both weekends of a group. */
export const SPIRITUAL_DIRECTOR_TEAM: Slot[] = [
  slot('Head Spiritual Director', 'lead', 'Grace'),
  slot('Spiritual Director', 'lead', 'Obstalces to Grace'),
  slot('Spiritual Director', 'lead', 'Life in Grace'),
  slot('Spiritual Director Trainee', 'basic', 'Sacred Moments of Grace'),
]

export const BASIC_ROLES: Role[] = [
  'Dining',
  'Palanca',
  'Table',
  'Dorm',
  'Floater',
  'Prayer',
  'Chapel',
  'Mobile',
]

export const HEAD_ROLES: Role[] = [
  'Head Dining',
  'Head Palanca',
  'Head Table',
  'Head Dorm',
  'Head Prayer',
  'Head Chapel',
  'Head Music',
  'Head Tech',
  'Head Mobile',
]

export const TEAM_FORMS = [
  'statement_of_belief',
  'commitment_form',
  'release_of_claim',
  'camp_waiver',
  'info_sheet',
] as const

// -----------------------------------------------------------------------------
// Candidate profiles — the life situations the review flow needs to handle
// -----------------------------------------------------------------------------

export type CandidateProfile = {
  maritalStatus: string
  spouseAttended: boolean | null
  isChristian: boolean | null
  clergy: boolean
  friendsAttending: boolean
  reason: string
  medical: string
  homeEnvironment: string
  godEvidence: string
}

export const CANDIDATE_PROFILES: CandidateProfile[] = [
  {
    maritalStatus: 'Married',
    spouseAttended: true,
    isChristian: true,
    clergy: false,
    friendsAttending: true,
    reason:
      'My spouse came back from their weekend changed. I want what they found.',
    medical: 'High blood pressure (controlled with medication)',
    homeEnvironment: 'Married with 2 children',
    godEvidence: 'Asking good questions about faith at home',
  },
  {
    maritalStatus: 'Single',
    spouseAttended: null,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason: 'Seeking a deeper relationship with Christ and an authentic faith.',
    medical: 'None',
    homeEnvironment: 'Single, career focused',
    godEvidence: 'Recently joined a small group',
  },
  {
    maritalStatus: 'Divorced',
    spouseAttended: null,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason:
      'Going through a hard season after my divorce. Looking for healing.',
    medical: 'Type 2 diabetes (diet controlled), previous knee surgery',
    homeEnvironment: 'Divorced, shares custody of two teenagers',
    godEvidence: 'Leaning on church community through the divorce',
  },
  {
    maritalStatus: 'Single',
    spouseAttended: null,
    isChristian: false,
    clergy: false,
    friendsAttending: false,
    reason:
      'Raised in church but walked away. Want to find out if this is real.',
    medical: 'Asthma (uses inhaler)',
    homeEnvironment: 'Lives alone, recently moved to the area',
    godEvidence: 'Started attending services again this year',
  },
  {
    maritalStatus: 'Widowed',
    spouseAttended: true,
    isChristian: true,
    clergy: false,
    friendsAttending: true,
    reason:
      'Lost my spouse last year. I need to reconnect with God and community.',
    medical: 'Heart condition — takes blood thinners',
    homeEnvironment: 'Widowed, adult children out of state',
    godEvidence: 'Faith has carried them through grief',
  },
  {
    maritalStatus: 'Married',
    spouseAttended: false,
    isChristian: true,
    clergy: true,
    friendsAttending: false,
    reason:
      'I pour into my congregation every week and need to be poured into.',
    medical: 'None',
    homeEnvironment: 'Pastor, married with 3 children',
    godEvidence: 'Leads a growing congregation',
  },
  {
    maritalStatus: 'Separated',
    spouseAttended: false,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason: 'Trying to rebuild my marriage and my faith at the same time.',
    medical: 'Depression (in treatment with therapist and medication)',
    homeEnvironment: 'Separated, working on reconciliation',
    godEvidence: 'Attending counseling through church',
  },
  {
    maritalStatus: 'Engaged',
    spouseAttended: null,
    isChristian: true,
    clergy: false,
    friendsAttending: true,
    reason: 'Want a spiritual foundation before I get married next spring.',
    medical: 'Severe peanut allergy (carries EpiPen)',
    homeEnvironment: 'Engaged, wedding planned for next year',
    godEvidence: 'Couple attends premarital class at church',
  },
  {
    maritalStatus: 'Married',
    spouseAttended: false,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason: 'My spouse does not share my faith and I feel isolated.',
    medical: 'Gluten intolerance (celiac) — dietary accommodations needed',
    homeEnvironment: 'Married, unbelieving spouse',
    godEvidence: 'Faithful attendance despite little support at home',
  },
  {
    maritalStatus: 'Married',
    spouseAttended: true,
    isChristian: true,
    clergy: false,
    friendsAttending: true,
    reason: 'Busy church leader who feels spiritually dry. Need renewal.',
    medical: 'Sleep apnea (uses CPAP machine)',
    homeEnvironment: 'Married, empty nesters',
    godEvidence: 'Serves as a deacon',
  },
  {
    maritalStatus: 'Single',
    spouseAttended: null,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason: 'Single parent — I rarely get time to focus on my own faith.',
    medical: 'Anxiety (managed with medication)',
    homeEnvironment: 'Single parent of a 6-year-old',
    godEvidence: 'Brings their child to church every week',
  },
  {
    maritalStatus: 'Married',
    spouseAttended: false,
    isChristian: true,
    clergy: false,
    friendsAttending: false,
    reason: 'Caregiver for my mother. I am worn out and need to rest in God.',
    medical: 'Back injury — needs a lower bunk',
    homeEnvironment: 'Married, caring for an aging parent at home',
    godEvidence: 'Prays faithfully through a demanding season',
  },
]
