/**
 * Reseeds the LOCAL Supabase database with a world positioned at one point in
 * the weekend cycle, relative to today.
 *
 *   bun run seed [phase] [--date YYYY-MM-DD] [--print] [--dry-run]
 *
 *   phase      pre-weekend (default) | weekend | post-weekend
 *   --date     pretend today is this date
 *   --print    write the SQL to stdout instead of applying it
 *   --dry-run  apply inside a transaction, then roll it back
 *   --yes      skip the confirmation prompt
 *
 * Wipes app data and every auth user (roles and site settings are kept), then
 * inserts the new world in one transaction. Every seeded account's password is
 * "password".
 */
import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { createInterface } from 'node:readline/promises'

import { daysBetween, insert, iso, parseDay, today, type Row } from './lib.ts'
import {
  buildWorld,
  PHASE_DESCRIPTIONS,
  PHASES,
  type Phase,
  type Summary,
  type Tables,
} from './world.ts'

const ROOT = join(import.meta.dirname, '..', '..')

const WIPED_TABLES = [
  'payment_transaction',
  'deposit_payments',
  'deposits',
  'team_form_completions',
  'draft_weekend_roster',
  'weekend_roster',
  'weekend_group_members',
  'users_experience',
  'candidate_info',
  'candidate_sponsorship_info',
  'candidates',
  'events',
  'weekend_group_fee_changes',
  'weekends',
  'weekend_groups',
  'user_roles',
  'user_medical_profiles',
  'email_log',
  'contact_information',
].map((t) => `public.${t}`)

function renderSql(tables: Tables, dryRun: boolean): string {
  const authUsers: Row[] = tables.people.map((p) => ({
    id: p.id,
    instance_id: '00000000-0000-0000-0000-000000000000',
    aud: 'authenticated',
    role: 'authenticated',
    email: p.email,
    encrypted_password: { raw: `current_setting('seed.password')` },
    email_confirmed_at: { raw: 'now()' },
    raw_user_meta_data: {
      raw: `'${JSON.stringify({ first_name: p.first, last_name: p.last, gender: p.gender }).replaceAll("'", "''")}'::jsonb`,
    },
    created_at: { raw: `'${iso(p.createdAt)}'::timestamptz` },
    updated_at: { raw: 'now()' },
    confirmation_token: '',
    email_change: '',
    email_change_token_new: '',
    recovery_token: '',
  }))

  const profileValues = tables.people
    .map(
      (p) =>
        `  ('${p.id}'::uuid, '${p.phone}', '${p.church.replaceAll("'", "''")}', '${p.attended}')`
    )
    .join(',\n')

  return `-- Generated by scripts/seed — do not edit by hand.
BEGIN;

SELECT set_config('seed.password', extensions.crypt('password', extensions.gen_salt('bf')), true);

-- Wipe ------------------------------------------------------------------------
TRUNCATE ${WIPED_TABLES.join(', ')} RESTART IDENTITY CASCADE;
UPDATE public.site_settings SET updated_by_user_id = NULL;
UPDATE public.community_encouragements SET updated_by_user_id = NULL;
DELETE FROM auth.users;

-- People ----------------------------------------------------------------------
${insert('auth.users', authUsers)}
INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
SELECT id, id, jsonb_build_object('sub', id::text, 'email', email), 'email', id::text, now(), now(), now()
FROM auth.users;

-- public.users rows come from the sync trigger; fill in the profile details.
UPDATE public.users u
SET phone_number = v.phone, church_affiliation = v.church, weekend_attended = v.attended
FROM (VALUES
${profileValues}
) AS v(id, phone, church, attended)
WHERE u.id = v.id;

${insert('public.user_roles', tables.userRoles)}
INSERT INTO public.contact_information (id, label, email_address)
VALUES ('preweekend-couple', 'Pre-Weekend Couple', 'sdavisde@gmail.com');

-- Weekends --------------------------------------------------------------------
${insert('public.weekend_groups', tables.weekendGroups)}
${insert('public.weekends', tables.weekends)}
${insert('public.events', tables.events)}

-- Team ------------------------------------------------------------------------
${insert('public.weekend_group_members', tables.groupMembers)}
${insert('public.weekend_roster', tables.roster)}
${insert('public.team_form_completions', tables.formCompletions)}
${insert('public.users_experience', tables.experience)}

-- Candidates ------------------------------------------------------------------
${insert('public.candidates', tables.candidates)}
${insert('public.candidate_sponsorship_info', tables.sponsorships)}
${insert('public.candidate_info', tables.candidateInfo)}

-- Payments --------------------------------------------------------------------
${insert('public.payment_transaction', tables.payments)}

${dryRun ? 'ROLLBACK;' : 'COMMIT;'}
`
}

function dbContainer(): string {
  const config = readFileSync(join(ROOT, 'supabase', 'config.toml'), 'utf8')
  const projectId = config.match(/^project_id\s*=\s*"([^"]+)"/m)?.[1]
  if (projectId === undefined)
    throw new Error('No project_id in supabase/config.toml')
  return `supabase_db_${projectId}`
}

function printSummary(summary: Summary, counts: Tables) {
  const rel = (day: Date) => {
    const d = daysBetween(summary.now, day)
    return d === 0 ? 'today' : d > 0 ? `in ${d}d` : `${-d}d ago`
  }
  const lines = [
    '',
    `Seeded phase "${summary.phase}" as of ${iso(summary.now)}`,
    `  ${PHASE_DESCRIPTIONS[summary.phase]}`,
    '',
    '  Groups:',
    ...summary.groups.map(
      (g) =>
        `    #${g.number} ${g.status.padEnd(8)} men ${iso(g.mens)} (${rel(g.mens)}), women ${iso(g.womens)}`
    ),
    '',
    '  #45 calendar:',
    ...[...summary.activeEvents]
      .sort((a, b) => a.day.getTime() - b.day.getTime())
      .filter((e) => !/(Sendoff|Serenade|Closing)$/.test(e.title))
      .map((e) => `    ${iso(e.day)}  ${e.title} (${rel(e.day)})`),
    '',
    '  You (sdavisde@gmail.com / password):',
    ...summary.sean.map((s) => `    - ${s}`),
    '',
    `  ${counts.people.length} users, ${counts.roster.length} roster rows, ${counts.candidates.length} candidates, ${counts.payments.length} payments`,
    '',
  ]
  console.error(lines.join('\n'))
}

/** Asks before wiping; --print and --dry-run leave the database untouched. */
async function confirm(phase: Phase): Promise<boolean> {
  console.error(
    `This will reset your local environment to "${phase}":\n  ${PHASE_DESCRIPTIONS[phase]}\n` +
      'All local app data and auth users will be replaced.'
  )

  if (!process.stdin.isTTY) {
    console.error('No terminal to confirm in — rerun with --yes to proceed.')
    return false
  }

  const prompt = createInterface({
    input: process.stdin,
    output: process.stderr,
  })
  const answer = await prompt.question('Continue? [y/N] ')
  prompt.close()
  return /^y(es)?$/i.test(answer.trim())
}

async function main() {
  const args = process.argv.slice(2)
  const flag = (name: string) => args.includes(name)
  const dateIndex = args.indexOf('--date')
  const now = dateIndex >= 0 ? parseDay(args[dateIndex + 1]) : today()
  const phase = (args.find(
    (a, i) => !a.startsWith('--') && args[i - 1] !== '--date'
  ) ?? 'pre-weekend') as Phase

  if (!PHASES.includes(phase)) {
    console.error(
      `Unknown phase "${phase}". Choose one of: ${PHASES.join(', ')}`
    )
    process.exit(1)
  }

  const { tables, summary } = buildWorld(phase, now)
  const sql = renderSql(tables, flag('--dry-run'))

  if (flag('--print')) {
    process.stdout.write(sql)
    return
  }

  if (!flag('--dry-run') && !flag('--yes') && !(await confirm(phase))) {
    console.error('Aborted — nothing was changed.')
    process.exit(1)
  }

  const container = dbContainer()
  const result = spawnSync(
    'docker',
    [
      'exec',
      '-i',
      container,
      'psql',
      '-U',
      'postgres',
      '-d',
      'postgres',
      '-v',
      'ON_ERROR_STOP=1',
      '-q',
    ],
    { input: sql, encoding: 'utf8' }
  )

  if (result.error !== undefined || result.status !== 0) {
    console.error(result.error?.message ?? result.stderr)
    console.error(
      `\nSeeding failed — is the local stack running (bun run db:start)? Container: ${container}`
    )
    process.exit(1)
  }

  if (flag('--dry-run')) {
    console.error('Dry run applied cleanly and was rolled back.')
  }
  printSummary(summary, tables)
}

void main()
